source 'https://rubygems.org'

# Microframework for web applications
gem 'goofy', '~> 1.0.0', :require => ['goofy','goofy/controller']
# A micro library providing Ruby objects with Publish-Subscribe capabilities
gem 'wisper'
# A wonderfully simple way to load your code
gem 'require_all'

group :test, :development do
  # Behaviour Driven Development for Ruby
  gem 'rspec'
end
